### ISSUE TITLE
`sw x1, 128(x2)` unexpected behavior

### ISSUE THREAD

**Issue by Savioor** [shooshx/corewars8086_js#11]
This command should write the contents of x1 into the address that comes 128 bytes after the address x2 point to, but instead, it writes it exactly to the address x2 points to.

I also tried to use 64 instead of 128 but the same behaviour was observed.

**Comment by shooshx** [comment]
worked on in https://github.com/westerndigitalcorporation/corewars-risc-v/issues/15
