### ISSUE TITLE
0xCCCC inserted after `bnez` or `beqz` instruction

### ISSUE THREAD

**Issue by Savioor** [shooshx/corewars8086_js#12]
After the `bnez` and `beqz` instruction, regardless of register and offset used, 0xCCCC is inserted.

For example, for this editor code:
![image](https://user-images.githubusercontent.com/25704274/52522854-83872e80-2c93-11e9-93de-5942b968e787.png)

This code is shown in debug mode:
![image](https://user-images.githubusercontent.com/25704274/52522866-9699fe80-2c93-11e9-928b-46b5783acf84.png)

**Comment by shooshx** [comment]
worked on in https://github.com/westerndigitalcorporation/corewars-risc-v/issues/15
