### ISSUE TITLE
`je` command jumps to relative location instead of absolute

### ISSUE THREAD

**Issue by Savioor** [shooshx/corewars8086_js#13]
As it says in the [official specifications](https://content.riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf):

> C.JR (jump register) performs an unconditional control transfer to the address in register `rs1`.  C.JR Rexpands to `jalr x0, rs1, 0`.

Despite this, using `jr` will behave like `j`, jumping by the value in the register from the current location.

**Comment by shooshx** [comment]
worked on in https://github.com/westerndigitalcorporation/corewars-risc-v/issues/
