### ISSUE TITLE
Incorrect assembly & disassembly of ADD when MOD == 0

### ISSUE THREAD

**Issue by Michael-K-Stein** [shooshx/corewars8086_js#14]
The instruction set of "ADD [disp], reg" (e.g. "ADD [0x50], AL") is compiled as "00 06 50 00 " instead of "00 05 50 00 00 00".
An ADD instruction where the reg or rm is only a displacement without a register should have the rem section set to 101 (binary), not 110. (Reference: [x86 Encoding Add edx, displacement](http://www.c-jump.com/CIS77/CPU/x86/lecture.html#X77_0150_encoding_add_edx_displacement) )

I think the bug arises from this function:
https://github.com/shooshx/corewars8086_js/blob/813434a46b56d3639dfe0c6f5592b31de0444b11/src/il/co/codeguru/corewars8086/utils/Disassembler.java#L213

**Comment by shooshx** [comment]
This looks like a difference in the encoding between 16 bit and 32 bit x86
see: 
http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=ADD+%5B0x50%5D%2C+AL&arch=x86-16&as_format=inline#assembly

This is emulating a 16bit machine so 00 06 50 00  is the correct encoding  
And anyway, this is the output from NASM and NASM is never wrong.

**Comment by Michael-K-Stein** [comment]
Pardon me, I hadn't seen there was a difference there between 16 and 32 bit.
My sincere apologies.
