### ISSUE TITLE
Debugging Issue, urgent!

### ISSUE THREAD

**Issue by orkinyo** [shooshx/corewars8086_js#18]
![image](https://user-images.githubusercontent.com/60312438/104833632-b637f980-58a2-11eb-97f9-511a70f3d752.png)
while debugging - I cannot see the instruction being executed, nor can I view the code I debug, (the address in the arena in the disassembly window start with 0000, and I cannot view the code of the survivors/zombies).
Thanks

**Comment by shooshx** [comment]
If you're opening an issue and then closing it, at the very least write what happened

**Comment by orkinyo** [comment]
Sry, 
the issue should still be opened.

**Comment by shooshx** [comment]
Yea, I'm seeing the problem, let me check

**Comment by shooshx** [comment]
should be good now, refresh the page.
I'll fix it better so that the view is able to stretch later

**Comment by orkinyo** [comment]
Thanks!
It's working for me too
