### ISSUE TITLE
Macros are not supported

### ISSUE THREAD

**Issue by shafzhr** [shooshx/corewars8086_js#20]
When debugging, macros are not shown correctly.
For example:
![image](https://user-images.githubusercontent.com/20832574/105625898-257a9400-5e35-11eb-8a6f-d2f775ccc3d2.png)
 
Will be shown as:
![image](https://user-images.githubusercontent.com/20832574/105625883-f9f7a980-5e34-11eb-8b0d-8cbac83a1ae7.png)

Note: the instructions are executed but it's just shown as 0xCC.

**Comment by shooshx** [comment]
fixed
