### ISSUE TITLE
האתר לא שומר את הקוד הנרשם לאחר שעוברים בין שני השורדים

### ISSUE THREAD

**Issue by idosharon** [shooshx/corewars8086_js#3]

**Comment by shooshx** [comment]
אתה יכול בבקשה לכתוב בדיוק את מה שעשית כדי שזה יקרה? אני לא זוכר בדיוק מה שהראית לי
לדוגמא:
- לחצתי על הכפתור bimp הראשון
- עשיתי פייסט לקוד
- עברתי לכפתור השני
- ראיתי שמשהו לא בסדר

**Comment by idosharon** [comment]
כן.

1. לחצתי על bimp 1
2. הדבקתי את הקוד שלי
3. עברתי ל bimp 2 
4. חזרתי ל bimp 1 והוא לא שמר את הקוד שלי
