### ISSUE TITLE
 בעיה בהעלאת קבצים מקומפלים

### ISSUE THREAD

**Issue by ilaial** [shooshx/corewars8086_js#6]
כשמעלים קובץ מקומפל הדיבאגר עושה לו דיקומפילציה ומריץ אותו בתור קוד שונה מהקוד מקור (בלי דיפיינס וכו') בניגוד לדיבאגר של קוד גורו שבו אפשר להריץ קודים מקומפלים.

**Comment by Savioor** [comment]
Are there any other issues except for `%define`'s missing? If not then everything works as it should.

**Comment by ilaial** [comment]
I don't think so,
Thanks
